# COURSE: Master math by coding in Python
## SECTION: Data types

#### https://www.udemy.com/course/math-with-python/?couponCode=MXC-DISC4ALL
#### INSTRUCTOR: sincxpress.com

Note about this code: Each video in this section of the course corresponds to a section of code below. Please note that this code roughly matches the code shown in the live recording, but is not exactly the same -- the variable names, order of lines, and parameters may be slightly different. 

In [ ]:
import numpy as np

# VIDEO: Numbers and strings

In [2]:
# ints vs. floats

c = 7
d = 7.0

print(c,d)

7 7.0


In [3]:
print( type(c) )
print( type(d) )

<class 'int'>
<class 'float'>


In [4]:
# implication of datatype for functions loops

for i in range(c): # vs d cant use a float in a range
    print(i)

0
1
2
3
4
5
6


In [5]:
# we can add numbers; can we "add" strings??
firstName = 'Mike'
lastName  = 'Cohen'

print( firstName + lastName ) # overloading- ?
print( firstName + ' ' + lastName )

MikeCohen
Mike Cohen


In [6]:
firstName * 3

'MikeMikeMike'

In [7]:
%whos

Variable    Type     Data/Info
------------------------------
c           int      7
d           float    7.0
firstName   str      Mike
i           int      6
lastName    str      Cohen


### Exercise

In [ ]:
### converting across datatypes

s1 = '4'
s2 = '4.7'
n1 = 5
n2 = 5.8

## convert strings to integers
print( int(s1) )
# print( int(s2) )


## string to floating-point
print( float(s1) )
print( int(float(s2)) ) # truncates it, doesn't round


## number to string
print( str(n1) )
print( str(n2) )


# VIDEO: Lists and numpy arrays

In [ ]:
aList = [0,1,2,3,4,5]
aList

In [ ]:
type(aList)

In [8]:
listList = [ 3,['3','4','5'],5,[4,5,6] ]
listList

[3, ['3', '4', '5'], 5, [4, 5, 6]]

In [ ]:
listList = [                # tuple
            3,              # a number- int
            ['3','h','5'],  # a list of strings
            5,              # another number- float
            [4,5,6]         # a list of numbers- double matrix
           ]

listList

In [10]:
# can we add lists?

aList = [0,1,2,3,4,5]
strList = ['0','1','2','3','4','5']

aList + strList
# aList + listList

[0, 1, 2, 3, 4, 5, '0', '1', '2', '3', '4', '5']

In [11]:
# multiply a list?
aList*3

# the principal here is 'overloading': One operation has multiple behaviors depending on the context

[0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5]

In [13]:
# lists vs. numpy arrays
import numpy as np

aList_np = np.array(aList)

print(aList)
print(aList_np)

[0, 1, 2, 3, 4, 5]
[0 1 2 3 4 5]


In [14]:
# now let's try multiplication again
# overlaoding- same * doing different results based on context
print(aList*3)
print(aList_np*3)

[0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5]
[ 0  3  6  9 12 15]


In [16]:
# scalar addition?
print(aList+ [3])
print(aList_np+3)

[0, 1, 2, 3, 4, 5, 3]
[3 4 5 6 7 8]


### Exercise

In [17]:
# regular method
for idx,item in enumerate(listList):
    print(f'List element {idx} is {item} and is of type {type(item)}.')

List element 0 is 3 and is of type <class 'int'>.
List element 1 is ['3', '4', '5'] and is of type <class 'list'>.
List element 2 is 5 and is of type <class 'int'>.
List element 3 is [4, 5, 6] and is of type <class 'list'>.


In [18]:
# advanced method to print out only the type
for idx,item in enumerate(listList):
    t = str(type(item))[8:] 
    apost = t.find("'")
    print(f'List element {idx} is {item} and is of type {t[:apost]}.')

List element 0 is 3 and is of type int.
List element 1 is ['3', '4', '5'] and is of type list.
List element 2 is 5 and is of type int.
List element 3 is [4, 5, 6] and is of type list.
